var mongoose=require("mongoose");

var OutletSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        unique:true
    },
    location:{
        address:{
            type:String,
            required:true,
        },
        pinCode:{
            type:Number,
            required:true
        },
        city:{
            type:String,
            required:true
        }
    }, 
    outletAdminId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"employee",
    },
    type:{
        type:String,
    },
    brand:{
        _id:{
            type:mongoose.Schema.Types.ObjectId,
            required:false,
            ref:"outlet",
        },
        name:{
            type:String,
            required:true
        }
    },
    products:[{
        product:{
            name:{
                type:String,
                trim:true,
               
            },
            price:{
                type:Number,
                required:true
            },
            img:{
                type:String,
                
            },
            description:{
                type:String,
            },
            categoryId:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"category"
            },
            categoryName:{
                type:String
            },
            _id:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"product"
            }

        }
    }
    ],
    description:{
        type:String,
        required:true,
        trim:true
    },
    contactInfo:{
        number:{
            type:Number,
            unique:true
        },
        email:{
            type:String,
            unique:true,
            trim:true
        }
    },
    isDeleted:{
        type:Boolean,
        default:false
    },
    isActive:{
        type:Boolean,
        default:true
    }
},{timestamps:true});
module.exports=mongoose.model("outlet",OutletSchema);