var mongoose=require("mongoose");

var outletSchema=new mongoose.Schema({
    outletName:{
        type:String,
        required:true,
        trim:true,
        unique:true
    },
    outletPinCode:{
        type:Number,
        required:true
    },
    outletAdminId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"employee",
    },
    brandId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"brand",
        required:true
    },
    products:[{
        product:{
            name:{
                type:String,
                trim:true,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            img:{
                type:String,
                
            },
            description:{
                type:String,
            }
        }
    }
    ],
    isDeleted:{
        type:Boolean,
        default:false
    },
    isActive:{
        type:Boolean,
        default:true
    }
},{timestamps:true});
module.exports=mongoose.model("outlet",outletSchema);